# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
